version: '2'
services:

  rails:
    build: ./rails_app
    image: erikperkins/rails_app
    command: bin/rails server --port 3001 --binding 0.0.0.0
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
    ports:
      - 3001:3001
    links:
      - redis
      - postgres
    volumes:
      - ./rails_app/:/rails_app/

  flask:
    build: ./flask_app
    image: erikperkins/flask_app
    command: python main.py
    ports:
      - 3002:3002
    depends_on:
      - postgres
    volumes:
      - ./flask_app/:/flask_app/

  snap:
    build: ./snap_app
    image: erikperkins/snap_app
    command: snapapp -p 3003
    ports:
      - 3003:3003
    depends_on:
      - postgres

  scalatra:
    build: ./scalatra_app
    image: erikperkins/scalatra_app
    command: catalina.sh run
    ports:
      - 8080:8080
    depends_on:
      - postgres

  nginx:
    image: nginx:1.11.6
    ports:
      - 80:80
      - 3101:3101
      - 3102:3102
      - 3103:3103
      - 3104:3104
      - 3105:3105
    links:
      - rails
      - flask
      - snap
      - scalatra
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/nginx.development.conf:/etc/nginx/nginx.conf"
      - "./nginx/html/:/etc/nginx/html/"
      - "./rails_app/public/:/var/www/public"

  postgres:
    image: postgres:9.5.5
    volumes:
      - ./postgres/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql
    expose:
      - 5432

  redis:
    image: redis:3.2.5
    expose:
      - 6379

  resque-worker:
    image: erikperkins/rails_app
    links:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      QUEUE: '*'
      LOGGING: 1
    command: bin/bundle exec rake environment resque:work
    volumes_from:
      - rails

  resque-scheduler:
    image: erikperkins/rails_app
    links:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
    command: bin/bundle exec rake environment resque:scheduler
    volumes_from:
      - rails

  rabbitmq:
    image: rabbitmq:3.6.6
    expose:
      - 15672
