version: '2'

services:
  rails:
    image: erikperkins/rails_app
    entrypoint: /rails_app/docker-entrypoint.sh
    command: bin/rails server --port 80 --binding 0.0.0.0
    environment:
      RAILS_ENV: production
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
      REDIS_URL: redis://52.37.63.163:6379
      REDIS_HOST: 52.37.63.163
      PHOENIX_HOST: 52.38.13.88
      FLASK_HOST: 52.36.236.17
      SCALATRA_HOST: scalatra
    expose:
      - 80
    links:
      - postgres
    volumes:
      - public:/rails_app/public/

  scalatra:
    image: erikperkins/scalatra_app
    command: catalina.sh run
    expose:
      - 80

  snap:
    image: erikperkins/snap_app
    command: snapapp -p 80
    expose:
      - 80
    links:
      - postgres

  golang:
    image: erikperkins/golang_app
    command: /golang_app/golang_app
    expose:
      - 80

  iron:
    image: erikperkins/iron_app
    command: /iron_app/target/release/iron_app
    expose:
      - 80

  nginx:
    image: nginx:1.11.6
    ports:
      - 80:80
      - 443:443
    links:
      - rails
      - snap
      - scalatra
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/nginx.production.conf:/etc/nginx/nginx.conf"
      - "./nginx/html/:/etc/nginx/html/"
      - public:/var/www/public/

  postgres:
    image: postgres:9.5.5
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./postgres/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql
    expose:
      - 5432

  resque-worker:
    image: erikperkins/rails_app
    environment:
      RAILS_ENV: production
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
      REDIS_URL: redis://52.37.63.163:6379
      REDIS_HOST: 52.37.63.163
      FLASK_HOST: 52.36.236.17
      SCALATRA_HOST: "scalatra"
      QUEUE: '*'
      LOGGING: 1
    command: bin/bundle exec rake environment resque:work

  resque-scheduler:
    image: erikperkins/rails_app
    environment:
      RAILS_ENV: production
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
      REDIS_URL: redis://52.37.63.163:6379
      REDIS_HOST: 52.37.63.163
      FLASK_HOST: 52.36.236.17
      SCALATRA_HOST: "scalatra"
    command: bin/bundle exec rake environment resque:scheduler

volumes:

  public:
    driver: local

  postgres:
    driver: local
