version: '2'

services:
  rails:
    image: erikperkins/rails_app
    entrypoint: /rails_app/docker-entrypoint.sh
    command: bin/rails server --port 3001 --binding 0.0.0.0
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
    expose:
      - 3001
    links:
      - postgres
      - redis
    volumes:
      - public:/rails_app/public/

  flask:
    image: erikperkins/flask_app
    command: uwsgi --ini uwsgi.ini
    expose:
      - 3002

  snap:
    image: erikperkins/snap_app
    command: snapapp -p 3003
    expose:
      - 3003
    links:
      - postgres

  scalatra:
    image: erikperkins/scalatra_app
    command: catalina.sh run
    expose:
      - 8080
    links:
      - postgres

  nginx:
    image: nginx:1.11.6
    ports:
      - 80:80
    links:
      - rails
      - flask
      - snap
      - scalatra
      - rabbitmq
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/nginx.production.conf:/etc/nginx/nginx.conf"
      - "./nginx/html/:/etc/nginx/html/"
      - public:/var/www/public/

  postgres:
    image: postgres:9.5.5
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./postgres/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql
    expose:
      - 5432

  redis:
    image: redis:3.2.5
    expose:
      - 6379

  resque-worker:
    image: erikperkins/rails_app
    links:
      - redis
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
      QUEUE: '*'
      LOGGING: 1
    command: bin/bundle exec rake environment resque:work

  resque-scheduler:
    image: erikperkins/rails_app
    links:
      - redis
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      RUBY_SECRET_KEY_BASE: ${RUBY_SECRET_KEY_BASE}
    command: bin/bundle exec rake environment resque:scheduler

  rabbitmq:
    image: rabbitmq:3.6.6-management
    expose:
      - 5672
      - 15672

  celery-worker:
    image: erikperkins/flask_app
    links:
      - rabbitmq
    command: celery -A main.celery worker

volumes:

  public:
    driver: local

  postgres:
    driver: local
