version: '2'

services:

  phoenix:
    image: erikperkins/phoenix_app
    entrypoint: /phoenix_app/docker-entrypoint.sh
    environment:
      MIX_ENV: prod
      PORT: 80
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      REDIS_HOST: 52.37.63.163
      RABBITMQ_HOST: 52.37.63.163
    command: mix phoenix.server
    restart: on-failure
    ports:
      - 80:80

  snap:
    image: erikperkins/snap_app
    command: snapapp -p 80
    restart: on-failure
    ports:
      - 8001:80

  golang:
    image: erikperkins/golang_app
    command: /golang_app/golang_app
    restart: on-failure
    ports:
      - 8002:80

  iron:
    image: erikperkins/iron_app
    command: /iron_app/target/release/iron_app
    restart: on-failure
    ports:
      - 8003:80
