version: '2'

services:

  postgres:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.7
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:

  postgres:
    driver: local
